### ISSUE TITLE
Specify license

### ISSUE THREAD

**Issue by chrisrosset** [al-caughey/YAMon-v4#8]
First of all, thank you for building and publishing YAMon!

What is the license situation here? I found [an old reddit comment](https://old.reddit.com/r/canada/comments/1uoobz/60_gigs_of_usage_came_out_of_nowhere_so_i_called/celcal1/) which states the scripts are open-source but the comment refers to v1.

**Comment by al-caughey** [comment]
Can I ask what are your licensing interests and/or concerns?  

I've been freely sharing the source code for 7 years now.  Over that time, I have stated repeatedly and emphatically that I have no time (or interest) in mining, selling, or sharing usage information. I don't mind if you use & distribute the software but I'm definitely not interested in someone else profiting from it (I certainly haven't... LOL).

I've created this repository so that the larger community can contribute the the maintenance and development...

I have added the following text to the README.md on the front page of the repository:
>Permission to use and/or distribute this software for any purpose without fee is hereby granted.

I will insert that in to key source files as well

**Comment by chrisrosset** [comment]
I wanted to know for certain whether this code is open-source. I've encountered code (even published on GitHub) which was read-only - no modifications allowed.

If you create a `LICENSE.md` file in the root of your repo (assuming the license is standard), GitHub will automatically display it (like here https://github.com/home-assistant/core).
